/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import glbModel from './room_final.glb';
import { GLTFResult } from "./gltfResult";
import Table from "./Table/Table";
import Chair from "./Chair/Chair";
import Closet from "./Closet/Closet";
import Window from "./Window/Window";
import Door from "./Door/Door";
import Laptop from "./Laptop/Laptop";
import MainLamp from "./MainLamp/MainLamp";
import Walls from "./Walls/Walls";
import AlarmClock from "./AlarmClock/AlarmClock";
import BedsideTable from "./BedsideTable/BedsideTable";
import Nintendo from "./Nintendo/Nintendo";
import { Radio } from "./Table/Radio/Radio";
import Drawer from "./Drawer/Drawer";
import Bed from "./Bed/Bed";
import PostIts from "./Table/PostIts/PostIts";
import ProjectFrames from "./ProjectFrames/ProjectFrames";
import Floor from "./Floor/Floor";

export function RoomModel({ isDarkMode, time, pointerRef }: { isDarkMode: boolean; time: string, pointerRef: any }) {
  const { nodes, materials } = useGLTF(glbModel) as GLTFResult;
  return (
    <group dispose={null}>
      <group name="Scene">
        <Walls nodes={nodes} materials={materials}/>
        <Floor nodes={nodes} materials={materials}/>
        <MainLamp nodes={nodes} materials={materials} />

        <Radio nodes={nodes} materials={materials}/>
        <Table nodes={nodes} materials={materials} />
        <PostIts nodes={nodes} materials={materials} />
        
        <Chair nodes={nodes} materials={materials} />
        
        <Closet nodes={nodes} materials={materials}/>
        
        <BedsideTable nodes={nodes} materials={materials}/>
        
        <AlarmClock nodes={nodes} materials={materials} timeString={time}/>
        
        <Drawer nodes={nodes} materials={materials} /> 


        <Bed nodes={nodes} materials={materials} isDarkMode={isDarkMode} pointerRef={pointerRef}/>
        
        
        <Window nodes={nodes} materials={materials} darkMode={isDarkMode}/>
        
        <Door nodes={nodes} materials={materials} />


        <Laptop nodes={nodes} materials={materials} />

        <ProjectFrames nodes={nodes} materials={materials} />

        <Nintendo nodes={nodes} materials={materials}/>
      </group>
    </group>
  );
}

useGLTF.preload(glbModel);